PreCommit:
  JsonSyntax:
    enabled: true
    include:
      - '*.json'
      - '.sublimelinterrc'

  Pep257:
    enabled: true
    flags: ['--ignore=D202']

  PythonFlake8:
    enabled: true
    flags: ['--max-line-length=120']

  TravisLint:
    enabled: true

  YamlSyntax:
    enabled: true
